# Generated by Django 3.2.4 on 2021-06-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('cpf', models.CharField(max_length=20, verbose_name='cpf')),
                ('rg', models.CharField(max_length=20, verbose_name='rg')),
                ('data_nasc', models.DateField(auto_now=True, verbose_name='data_nasc')),
                ('sexo', models.CharField(max_length=10, verbose_name='sexo')),
                ('mae', models.CharField(max_length=255, verbose_name='mae')),
                ('pai', models.CharField(max_length=255, verbose_name='pai')),
                ('celular', models.CharField(max_length=20, verbose_name='celular')),
                ('altura', models.FloatField(verbose_name='altura')),
                ('peso', models.FloatField(verbose_name='peso')),
                ('tipo_sanguineo', models.CharField(max_length=5, verbose_name='tipo_sanguineo')),
            ],
        ),
    ]
