# Generated by Django 3.2.4 on 2021-06-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.IntegerField()),
                ('rg', models.IntegerField()),
                ('data_nasc', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('mae', models.CharField(max_length=100)),
                ('pai', models.CharField(max_length=100)),
                ('celular', models.IntegerField()),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('tipo_sanguineo', models.CharField(max_length=4)),
            ],
        ),
    ]
