# Generated by Django 3.2.4 on 2021-06-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youngers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='person',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='person',
            name='data_nasc',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mae',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pai',
        ),
        migrations.RemoveField(
            model_name='person',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='person',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='person',
            name='tipo_sanguineo',
        ),
    ]
